### ISSUE TITLE
script 4-test-counter.js is empty

### ISSUE THREAD

**Issue by itsab11** [Antony-SS/Final-Template-Backend-Algorand-SongVote#1]
Hello, 

first of all, thank you for creating this tutorial. Even though I have litte experience in python and even less in javascript, it is quite easy to follow along.
However, I cannot get past part 13 "Testing the contract"
In the introduction, you wrote: "Head to 4-testing-counter.js. I’ve included import statements, a helper function to read from global state, and code to connect to a client."
But in reality, this file is empty. 
I´d be very thankful if you could correct this issue.

Best regards

**Comment by Antony-SS** [comment]
Will work on fixing this now!

**Comment by Antony-SS** [comment]
Should be fixed, let me know if you have any other issues.
